### ISSUE TITLE
Python 3.8 ModuleNotFoundError: No module named 'nsl.stac.destinations'

### ISSUE THREAD

**Issue by felytic** [nearspacelabs/stac-client-python#55]
Hello Near Space Labs!

Could you, please, help me with the installation of your client? I have an error, that is in the title.

## Steps to reproduce
1. Create virtualenv:
```
$ virtualenv --python=python3.8 .venv
```
2. Activate it:
```
$ source ./.venv/bin/activate
```
3. Install `nsl.stac`
```
(.venv) $ pip3 install nsl.stac
```
Installed libs:
```
(.venv) $ pip3 freeze                                                                                                                                 15:08 [130]
boto3==1.20.21
botocore==1.23.21
cachetools==4.2.4
certifi==2021.10.8
charset-normalizer==2.0.9
decorator==5.1.0
epl.protobuf.v1==1.0.3
google-api-core==2.3.0
google-auth==2.3.3
google-cloud-core==2.2.1
google-cloud-storage==1.43.0
google-crc32c==1.3.0
google-resumable-media==2.1.0
googleapis-common-protos==1.54.0
grpcio==1.42.0
grpcio-tools==1.42.0
idna==3.3
jmespath==0.10.0
nsl.stac==1.1.5
protobuf==3.19.1
py==1.11.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
python-dateutil==2.8.2
requests==2.26.0
retry==0.9.2
rsa==4.8
s3transfer==0.5.0
six==1.16.0
urllib3==1.26.7
```
4. Run python:
```
(.venv) $ python3
Python 3.8.12 (default, Sep 30 2021, 15:06:31) 
[GCC 11.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>
```
5. Try to import:
```
>>> from nsl.stac import NSLClient
using NSL_ID __________________________ specified in env var
nsl client connecting to stac service at: api.nearspacelabs.net:9090

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'NSLClient' from 'nsl.stac' (/home/felytic/dev/temp/.venv/lib/python3.8/site-packages/nsl/stac/__init__.py)
```
I've also tried to import from `nsl.stac.client` explicitly:
```
>>> from nsl.stac.client import NSLClient
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/felytic/dev/temp/.venv/lib/python3.8/site-packages/nsl/stac/client.py", line 26, in <module>
    from nsl.stac.destinations import BaseDestination, MemoryDestination
ModuleNotFoundError: No module named 'nsl.stac.destinations'
```
## System info
```
$ uname -a                                                                                                                                      
Linux hp 5.14.16-arch1-1 #1 SMP PREEMPT Tue, 02 Nov 2021 22:22:59 +0000 x86_64 GNU/Linux
```

**Comment by felytic** [comment]
## UPD
Two additional observations:
1. Package doesn't have [destinations](https://github.com/nearspacelabs/stac-client-python/tree/master/nsl/stac/destinations) folder after installation
2. Everything works well with python 3.9

**Comment by sunny-g** [comment]
Fixed in #56

**Comment by sunny-g** [comment]
Thank you @felytic for the thorough report :)
